# Stage 1: Compile the planner
Bootstrap: docker
From: ubuntu:18.04
Stage: build

%files
    . /planner

%post
    apt-get update
    apt-get install --no-install-recommends -y \
    build-essential \
    g++\
    gcc\
    make\
    cmake\
    python\
    xutils-dev \
    scons \
    gcc-multilib \
    flex \
    bison \
    python3 \
    libboost-dev \
    libjudy-dev \
    libboost-program-options-dev \
    g++-multilib \
    libgmp3-dev \
    python-pyparsing\
    gawk\
    pypy\
    python-pyparsing\
    python-psutil\
    libncurses5-dev

    MAKE_FLAGS="-j 16"
    export MAKE_FLAGS
    ./planner/build

    # TODO: Strip all binaries
    strip --strip-all /planner/src/preprocess-old/preprocess


# Stage 2: Run the planner
Bootstrap: docker
From: ubuntu:18.04
Stage: run

%files from build
    # TODO: Copy only the necessary files from these directories.
    /planner/src/arvand/
    /planner/src/preprocess-old/preprocess
    /planner/src/probe/
    /planner/src/translate-old/
    /planner/src/yahsp2-mt/

%post
    apt-get update
    apt-get -y install --no-install-recommends python
    apt-get clean
    rm -rf /var/lib/apt/lists/*

%runscript
    DOMAINFILE=$1
    PROBLEMFILE=$2
    PLANFILE=$3
    PLANNER=$4

    /planner/src/"$PLANNER"/plan "$DOMAINFILE" "$PROBLEMFILE" "$PLANFILE"


## Update the following fields with meta data about your submission.
## Please use the same field names and use only one line for each value.
%labels
Name        IBaCoP-2018
Description New version IBaCoP Agile  Static selection, it always present the same configuration for all problems or domains.
Authors     Isabel Cenamor <icenamorg@gmail.com>, Tomas de la Rosa <trosa@inf.uc3m.es> and Fernando Fernandez <ffernand@inf.uc3m.es>
SupportsDerivedPredicates yes
SupportsQuantifiedPreconditions no
SupportsQuantifiedEffects no
