# Stage 1: Compile the planner
Bootstrap: docker
From: ubuntu:xenial
Stage: build

%files
    . /planner

%post
    ## Install all necessary dependencies.
    apt-get update
    apt-get -y install --no-install-recommends cmake g++ gcc make bison flex zlib1g-dev python coreutils default-jre default-jdk ant unzip

    ## Build the planner
    cd /planner
    make
    strip --strip-all /planner/incplan-lgl


# Stage 2: Run the planner
Bootstrap: docker
From: ubuntu:xenial
Stage: run

# Copy planner binary and required files from Stage 1.
%files from build
    
    /planner/incplan-lgl 
    /planner/plan-agl.sh
    /planner/plan-sat.sh

    #/planner/build.xml
    #/planner/fl-ipc18.xml
    /planner/fl-ipc18.jar 
    /planner/incplan/lib
    /planner/translate
    
%post
    ## Install only dependencies for running the planner.
    apt-get update
    apt-get -y install python3-minimal
    apt-get -y install default-jre
    ## Remove unnecessary files to keep the image small.
    rm -rf /var/lib/apt/lists/*


# The runscript is called whenever the container is used to solve an instance.
%runscript

    /planner/plan-$4.sh $1 $2 $3


## Update the following fields with meta data about your submission.
## Please use the same field names and use only one line for each value.
%labels
Name        freelunch-doubly-relaxed
Description Incremental Satisfiasfiability based Planning using the relaxed relaxed encoding of freelunch
Authors     Tomas Balyo <tomas.balyo@kit.edu> and Stephan Gocht <gocht@kth.se>
SupportsDerivedPredicates no
SupportsQuantifiedPreconditions no
SupportsQuantifiedEffects no
