Bootstrap: docker
From: ubuntu:18.04

%files
    . /planner

%post
    ## Install all dependencies.
    apt-get update
    apt-get -y install bison flex make xutils-dev g++-multilib scons

    ## Build the planner.
    cd /planner
    ./build
    ls -la
    ls -la src/parser-ff

    ## Strip binary.
    strip --strip-all /planner/probe

    ## Remove packages unneeded for running the planner.
    apt-get -y autoremove bison flex make xutils-dev g++ scons
    rm -rf /var/lib/apt/lists/*

    ## Keep binaries and scripts.
    mkdir -p /compiled-planner/
    cp /planner/probe /compiled-planner/
    mkdir -p /compiled-planner/src/parser-ff/
    cp /planner/src/parser-ff/libff.a /compiled-planner/src/parser-ff/
    cp /planner/plan /compiled-planner/

    rm -rf /planner
    mv /compiled-planner /planner

%runscript
    DOMAINFILE=$1
    PROBLEMFILE=$2
    PLANFILE=$3

    /planner/plan $DOMAINFILE $PROBLEMFILE $PLANFILE
