#!/bin/bash
#planners=("preprocess-old" "preprocess" "features" "parser" "search" "search-mercury" "arvand" "lama-2008" "lamar" "lpg" "madagascar" "probe" "yahsp2-mt")
planners=("features" "parser" "search-mercury" "probe" "preprocess-old" "preprocess" "preprocess-old" "search" "arvand" "lamar" "mercury" "jasper" "siw" "bfs-f" "yahsp2-mt" "lama-2008")    


cd "$(dirname "$0")"
ROOT=$PWD


for item in ${planners[*]}
do
	planner_path="$ROOT"/src/"$item"
	echo -e "\n**************************"
	echo "*** Compiling" $item "***" 
	echo -e "**************************\n"
	cd $planner_path
	./build

	if [ $? -ne 0 ]; then
		echo -e "\nCompilation error when compiling:" $item 
		exit 1
	fi

done

echo -e "\nPlanner ready to the International Planning Competition 2018"
