#!/bin/bash

set -e

BASEDIR="$(dirname "$0")"
PWD="$(dirname "$3")"
# Paths to planner components
TRANSLATE="$BASEDIR/../translate/translate.py"
PREPROCESS="$BASEDIR/../preprocess/preprocess"
SEARCH="$BASEDIR/../search/downward"

if [ ! -f "$PWD/output.sas" ]; then
    echo "1. Running translator"
    if [[ -e "$2" ]]; then
        echo "Second argument is a file name: use two translator arguments."
        python2.7 "$TRANSLATE" "$1" "$2"
    else
        echo "Second argument is not a file name: auto-detect domain file."
       python2.7 "$TRANSLATE" "$1"
    fi
else
    echo "Skip the translate"
fi
if [ ! -f "$PWD/output" ]; then
    
    echo "2. Running preprocessor"
    "$PREPROCESS" < output.sas
    echo "End Running preprocessor"
else
    echo "Skip the preprocess"
fi
echo "3. Running search"
"$SEARCH" ipc seq-sat-fd-autotune-1 --plan-file "$3" < output;
echo

