excled_cols = [
    'domain', 'task_name', 
    'no','file',
    'problem_name',
    'domain_name',
]


ftcols_ftcomputed = [
    'cpt_fact_balance',
    'cpt_heuristics',
    'cpt_landmarks',
    'cpt_redblack',
]

ftcols_baseft = [
    # "domain",
    # "task_name",
    "requirements",
    "types",
    "objects",
    "predicates",
    "functions",
    "init",
    "goal",
    "actions",
    "axioms",
    "use_min_cost_metric",
    "generated_rules",
    "relevant_atoms",
    "auxiliary_atoms",
    "final_queue_length",
    "total_queue_pushes",
    "implied_effects_removed",
    "effect_conditions_simplified",
    "implied_preconditions_added",
    "translator_variables",
    "translator_derived_variables",
    "translator_facts",
    "translator_mutex_groups",
    "translator_total_mutex_groups_size",
    "translator_operators",
    "translator_task_size",
    "numberVariablesCG",
    "highLevelVariablesCG",
    "totalEdgesCG",
    "totalWeightCG",
    "veRatio",
    "weRatio",
    "wvRatio",
    "hvRatio",
    "inputEdgeCGMax",
    "inputEdgeCGAvg",
    "inputEdgeCGStd",
    "outputEdgeCGMax",
    "outputEdgeCGAvg",
    "outputEdgeCGStd",
    "inputWeightCGMax",
    "inputWeightCGAvg",
    "inputWeightCGStd",
    "outputWeightCGMax",
    "outputWeightCGAvg",
    "outputWeightCGStd",
    "inputEdgeHVMax",
    "inputEdgeHVAvg",
    "inputEdgeHVStd",
    "outputEdgeHVMax",
    "outputEdgeHVAvg",
    "outputEdgeHVStd",
    "inputWeightHVMax",
    "inputWeightHVAvg",
    "inputWeightHVStd",
    "outputWeightHVMax",
    "outputWeightHVAvg",
    "outputWeightHVStd",
    "numberVariablesDTG",
    "totalEdgesDTG",
    "totalWeigthDTG",
    "edVaRatioDTG",
    "weEdRatioDTG",
    "weVaRatioDTG",
    "inputEdgeDTGMax",
    "inputEdgeDTGAvg",
    "inputEdgeDTGStd",
    "outputEdgeDTGMax",
    "outputEdgeDTGAvg",
    "outputEdgeDTGStd",
    "inputWeightDTGMax",
    "inputWeightDTGAvg",
    "inputWeightDTGStd",
    "outputWeightDTGMax",
    "outputWeightDTGAvg",
    "outputWeightDTGStd", 
]

ftcols_fact_balance = [
   "num_relevant_facts",
    "num_actions",
    "h_max",
    "h_ff",
    "h_ff_ratio",
    "rp_fact_balance_min",
    "rp_fact_balance_avg",
    "rp_fact_balance_var",
    "rp_goal_balance_min",
    "rp_goal_balance_avg",
    "rp_goal_balance_var",
    
    "balance_Ratio",
    "Unbalance_Ratio",
    "Balance_Distorsion",
]

ftcols_heuristics = [
    "Additive ",
    "Blind",
    "Causal_graph",
    "Context-enhanced_additive",
    "FF",
    "Goal_count",
    "Landmark_count",
    "Landmark-cut",
    "Max",
]

ftcols_landmarks = [
    "n_landmarks",
    "numberEdges",
    "edVaratioLand",
    "numberFatherNodes",
    "numberChildrenNodes",
    "nodosbetween",
    "avginput",
    "maxinput",
    "stdinput",
    "avgoutput",
    "maxoutput",
    "stdoutput",
]

ftcols_redblack = [
    "blackVariables",
    "blackRootVariables",
    "redBlackVariables",
    "allpairsvaluesconnected",
    "allvaluesconnectedgoal",
    "blackstronglpyarents",
    "Maximaleffectsblack",
    "Hred-black",
]
