#! /bin/bash

cd preprocess
make "$@" || exit 1
cd ..

cd search
# here add meddly
cd meddly
./autogen.sh || exit 1
./configure CXXFLAGS="-O3" --without-gmp || exit 1
make "$@" || exit 1
make install || exit 1
cd ..

make "$@" STATE_VAR_BYTES=1 || exit 1
make "$@" STATE_VAR_BYTES=2 || exit 1
make "$@" STATE_VAR_BYTES=4 || exit 1
cd ..

type flex >& /dev/null
if [ $? != 0 ]; then
    echo cannot build validator: flex not found
    exit 1
fi

type bison >& /dev/null
if [ $? != 0 ]; then
    echo cannot build validator: bison not found
    exit 1
fi

cd VAL
make "$@" || exit 1
#cp validate ../
cd ..
