#! /bin/bash
echo "$#"
if [ $# -lt 4 ] || [ $# -gt 5 ]; then
    echo "usage: $(basename "$0") PLANNER_NAME DOMAIN PROBLEM PLAN_FILE [COST-BOUND]" 1>&2
    exit 1
fi

BASEDIR="$(dirname "$0")"
"$BASEDIR/plan" "$2" "$3" ipc-18 "$1" --plan-file "${@:4}"
